### ISSUE TITLE
ros-lunar/cmake_modules-0.4.1::ros-overlay - Unable to find either executable 'empy' or Python module 'em'

### ISSUE THREAD

**Issue by archenroot** [ros/ros-overlay#78]
dev-python/empy is not pulled automatically in - missing dependency config in ebuild..
**Detail:**
```
>>> Emerging (7 of 247) ros-lunar/cmake_modules-0.4.1::ros-overlay
 * cmake_modules-0.4.1-0.4.1.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                              [ ok ]
>>> Unpacking source...
>>> Unpacking cmake_modules-0.4.1-0.4.1.tar.gz to /tmp/portage/ros-lunar/cmake_modules-0.4.1/work
>>> Source unpacked in /tmp/portage/ros-lunar/cmake_modules-0.4.1/work
>>> Preparing source in /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1 ...
>>> Source prepared.
>>> Configuring source in /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1 ...
>>> Working in BUILD_DIR: "/tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build"
cmake -C /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/tmp/portage/ros-lunar/cmake_modules-0.4.1/image/opt/ros/lunar -DCMAKE_PREFIX_PATH=/opt/ros/lunar -DPYTHON_INSTALL_DIR=lib64/python3.5/site-packages -DPYTHON_EXECUTABLE=/usr/bin/ros-python-lunar -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build/gentoo_toolchain.cmake  /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1
loading initial cache file /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /tmp/portage/ros-lunar/cmake_modules-0.4.1/work/cmake_modules-0.4.1_build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/lunar
-- This workspace overlays: /opt/ros/lunar
-- Found PythonInterp: /usr/bin/ros-python-lunar (found version "1.4") 
-- Using PYTHON_EXECUTABLE: /usr/bin/ros-python-lunar
-- Using default Python package layout
-- Could NOT find PY_em (missing:  PY_EM) 
CMake Error at /opt/ros/lunar/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
Call Stack (most recent call first):
  /opt/ros/lunar/share/catkin/cmake/all.cmake:147 (include)
  /opt/ros/lunar/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:4 (find_package)

```
I installed empy:
```
ares ~ # equery meta empy
 * dev-python/empy [gentoo]
Maintainer:  python@gentoo.org (Python)
Upstream:    None specified
Homepage:    http://www.alcyone.com/software/empy/
Location:    /usr/portage/dev-python/empy
Keywords:    3.3-r1:0: amd64 ia64 ppc x86
Keywords:    3.3.2:0: ~amd64 ~arm ~ia64 ~ppc ~x86
License:     LGPL-2.1

......

*  dev-python/empy
      Latest version available: 3.3.2
      Latest version installed: 3.3.2
      Size of files: 135 KiB
      Homepage:      http://www.alcyone.com/software/empy/
      Description:   A powerful and robust templating system for Python
      License:       LGPL-2.1

```
Error persists even with installed empy...

**Comment by archenroot** [comment]
I am on following python:
ares ~ # python
Python 3.4.5 (default, Jun  5 2017, 12:15:32) 
[GCC 6.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by archenroot** [comment]
I have actually multiple catkins, so that could be a problem... and CATKING is from GENTOO tree
```
ares ~ # equery meta dev-util/catkin
 * dev-util/catkin [gentoo]
Maintainer:  ros@gentoo.org (Gentoo ROS Project)
Upstream:    Remote-ID:   ros/catkin ID: github
Homepage:    http://wiki.ros.org/catkin
Location:    /usr/portage/dev-util/catkin
Keywords:    0.7.6-r1:0: ~amd64 ~arm
Keywords:    9999:0: 
License:     BSD
ares ~ # equery meta dev-python/catkin_pkg
 * dev-python/catkin_pkg [gentoo]
Maintainer:  None specified
Upstream:    None specified
Homepage:    http://wiki.ros.org/catkin_pkg
Location:    /var/repo/ros-overlay/dev-python/catkin_pkg
Keywords:    0.3.1-r3:0: 
Keywords:    0.3.3:0: 
Keywords:    0.3.4:0: amd64 arm x86 ~arm64
Keywords:    9999:0: 
License:     BSD
ares ~ # equery meta ros-lunar/catkin
 * ros-lunar/catkin [ros-overlay]
Maintainer:  hunter@openrobotics.org (Hunter L. Allen)
Upstream:    Maintainer:  dthomas@osrfoundation.org (Dirk Thomas)
             Bugs-to:     https://github.com/ros-gbp/catkin/issues
Homepage:    https://wiki.ros.org
Location:    /var/repo/ros-overlay/ros-lunar/catkin
Keywords:    0.7.6:0: amd64 arm x86 ~arm64
License:     BSD

```
I will try to re-emerge....

this time it pulled **dev-python/catkin_pkg-0.3.4::**ros-overlay****

But:
```
>>> Installing (1 of 2) dev-python/catkin_pkg-0.3.4::ros-overlay

>>> Emerging (2 of 2) ros-lunar/catkin-0.7.6::ros-overlay
 * catkin-0.7.6-0.7.6.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                     [ ok ]
>>> Unpacking source...
>>> Unpacking catkin-0.7.6-0.7.6.tar.gz to /tmp/portage/ros-lunar/catkin-0.7.6/work
 * Applying various patches (bugfixes/updates) ...
 *   fix-destdir.patch ...                                                                                                                                            [ ok ]
 * Done with patching
>>> Source unpacked in /tmp/portage/ros-lunar/catkin-0.7.6/work
>>> Preparing source in /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6 ...
>>> Source prepared.
>>> Configuring source in /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6 ...
>>> Working in BUILD_DIR: "/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build"
cmake -C /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_PREFIX=/tmp/portage/ros-lunar/catkin-0.7.6/image/opt/ros/lunar -DCMAKE_PREFIX_PATH=/opt/ros/lunar -DPYTHON_INSTALL_DIR=lib64/python3.5/site-packages -DCATKIN_BUILD_BINARY_PACKAGE=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/gentoo_toolchain.cmake  /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6
loading initial cache file /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/lunar
-- Found PythonInterp: /usr/bin/python (found version "3.4.5") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Found PY_em: /usr/lib64/python3.4/site-packages/em.py  
-- Using empy: /usr/lib64/python3.4/site-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/test_results
-- Found gtest: gtests will be built
-- Using Python nosetests: /usr/bin/nosetests
ImportError: "from catkin_pkg.package import parse_package" failed: No module named 'catkin_pkg'
Make sure that you have installed "catkin_pkg", it is up to date and on the PYTHONPATH.
CMake Error at cmake/safe_execute_process.cmake:11 (message):
  execute_process(/usr/bin/python
  "/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6/cmake/parse_package_xml.py"
  "/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6/cmake/../package.xml"
  "/tmp/portage/ros-lunar/catkin-0.7.6/work/catkin-0.7.6_build/catkin/catkin_generated/version/package.cmake")
  returned error code 1
Call Stack (most recent call first):
  cmake/catkin_package_xml.cmake:63 (safe_execute_process)
  cmake/all.cmake:151 (_catkin_package_xml)
  CMakeLists.txt:8 (include)

```

I am not sure if there is some mess between ROS overlay and portage tree, I will try to examine.

**Comment by archenroot** [comment]
Your package catkin_pkg is installed in wrong way, whereas Gentoo tree is installed fine:

This is Gentoo one:
ares catkin_pkg # pip list |grep catkin
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
catkin-pkg (0.3.4)

Your package doesn't integrate in python system...

NOTE: You mark your ebuilds with amd64, but also those should be ~amd64 as these are unstable. Marking something as stable requires some period of time, bug fixing period, ebuild stabilization, etc...

Woloda

**Comment by allenh1** [comment]
I forgot to update the install instructions... Please don't emerge any overlay package that doesn't start with `ros-lunar`. Try removing the `dev-util` and the `dev-python` versions of catkin, as you won't need them.

As for the issue with `empy`, it seems that the `empy` doesn't copy the executable to the `/use/bin` directory. Any way to fix that? I think I just symlinked it in by hand and then forgot to find a real solution to it.

**Comment by allenh1** [comment]
Python 3.4 is also gonna be a problem... Let me fix the ebuild generator (currently hard codes in Python 3.5).

**Comment by archenroot** [comment]
Ok, I understand
empy - why not take ebuild from Gentoo?
Python - I can build with any version you ask me for.

Ladislav


2017-06-08 15:53 GMT+02:00 Hunter Allen <notifications@github.com>:

**Comment by allenh1** [comment]
So the gentoo empy ebuild appears to be the issue: it doesn't put the script in /usr/bin. I'll be more specific about this when I get to the office today, but I'd be interested to see what `equery files empy` outputs for you.

**Comment by archenroot** [comment]
Yes, no bin:
```
ares opencv # equery f =dev-python/empy-3.3.2::gentoo
 * Searching gentoo for empy3.3.2 in dev-python ...
 * Contents of dev-python/empy-3.3.2:
/usr
/usr/lib64
/usr/lib64/python2.7
/usr/lib64/python2.7/site-packages
/usr/lib64/python2.7/site-packages/em.py
/usr/lib64/python2.7/site-packages/em.pyc
/usr/lib64/python2.7/site-packages/em.pyo
/usr/lib64/python2.7/site-packages/empy-3.3.2-py2.7.egg-info
/usr/lib64/python3.4
/usr/lib64/python3.4/site-packages
/usr/lib64/python3.4/site-packages/__pycache__
/usr/lib64/python3.4/site-packages/__pycache__/em.cpython-34.pyc
/usr/lib64/python3.4/site-packages/__pycache__/em.cpython-34.pyo
/usr/lib64/python3.4/site-packages/em.py
/usr/lib64/python3.4/site-packages/empy-3.3.2-py3.4.egg-info
/usr/share
/usr/share/doc
/usr/share/doc/empy-3.3.2
/usr/share/doc/empy-3.3.2/README.bz2

```

**Comment by archenroot** [comment]
Ok, you are right, there is missing em.py script is missing...

**Comment by allenh1** [comment]
Here's the output on Ubuntu:

```
allenh1@machina ~
$ dpkg -L python-empy
/.
/usr
/usr/lib
/usr/lib/python2.7
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/em.py
/usr/lib/python2.7/dist-packages/empy-3.3.2.egg-info
/usr/share
/usr/share/doc
/usr/share/doc/python-empy
/usr/share/doc/python-empy/README.gz
/usr/share/doc/python-empy/copyright
/usr/share/doc/python-empy/changelog.Debian.gz
/usr/share/doc/python-empy/examples
/usr/share/doc/python-empy/examples/sample.em.gz
/usr/share/doc/python-empy/examples/sample.bench.gz
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/empy.1.gz
/usr/bin
/usr/bin/empy
```

Is there a use flag needed to make the bin?

In the meantime, I fixed it by doing this:
```
sudo chmod +x /usr/lib64/python3.5/site-packages/em.py
sudo ln -s /usr/lib64/python3.5/site-packages/em.py /usr/bin/empy
```

**Comment by archenroot** [comment]
I am also curious, how this should be handled in proper way, I did yesterday some quick search, but still not 100% clear to me..

**Comment by archenroot** [comment]
I raised bug: https://bugs.gentoo.org/show_bug.cgi?id=621288

**Comment by allenh1** [comment]
@achenroot thank you very much! It is definitely not very proper to symlink it... I just didn't want to wait for a fix if it wasn't broken type deal. But I definitely consider it a bug.

**Comment by allenh1** [comment]
For convenience, this was the first reply from the Gentoo people:

> The upstream build system does not install any scripts, so I don't see why we should either.

I think we should just write an ebuild to install it then. Would you like to do the honors, @archenroot ?

**Comment by archenroot** [comment]
I just red it, I have no problem with creating override, but I would like
to hear from DEVs, what is than the expected usage...? It is confusing.

2017-06-09 21:01 GMT+02:00 Hunter Allen <notifications@github.com>:

**Comment by allenh1** [comment]
> > So, how should it be called from command line?

> python2.7 -m em ...

Well, that's not exactly the response I was hoping for. But they are right, the upstream doesn't install it.

This is from `setup.py` from the current release.
```py
setup(
    name="empy",
    version="3.3.3",
    author="Erik Max Francis", 
    author_email="software@alcyone.com",
    url="http://www.alcyone.com/software/empy",
    license="%LICENSE",
    py_modules=["em", "emlib"],
    platforms=["unix", "linux", "win32"],
    description=DESCRIPTION,
    long_description=LONG_DESCRIPTION,
)
```

Maybe this should be considered more of a cmake problem? Or maybe the catkin cmake looks for the `/usr/bin/empy` instead of the python module?

**Comment by Alessandro-Barbieri** [comment]
>or Python module 'em'

Searches in the wrong folder

**Comment by archenroot** [comment]
Creating the symlink handle the issue as hack, but as proved this module should be used/detected in different way. Let's leave this one open.

**Comment by allenh1** [comment]
Glad to report that this is no longer an issue! I just did a fresh Gentoo install on a Raspberry Pi 3 and didn't need to make a symlink when building ROS.

**Comment by flabrosse** [comment]
Interestingly enough, updating my box now and getting this issue.

empy:

`eix empy
[I] dev-python/empy
     Available versions:  3.3-r1 ~3.3.2 {doc PYTHON_TARGETS="pypy pypy3 python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  3.3-r1(11:21:44 10/02/18)(-doc PYTHON_TARGETS="python2_7 -pypy")
     Homepage:            http://www.alcyone.com/software/empy/
     Description:         A powerful and robust templating system for Python`

and the fail emerge:

`>>> Emerging (1 of 68) ros-lunar/rostime-0.6.9::ros-overlay
 * rostime-lunar-release-0.6.9.tar.gz BLAKE2B SHA512 size ;-) ...        [ ok ]
>>> Unpacking source...
>>> Unpacking rostime-lunar-release-0.6.9.tar.gz to /var/tmp/portage/ros-lunar/rostime-0.6.9/work
>>> Source unpacked in /var/tmp/portage/ros-lunar/rostime-0.6.9/work
>>> Preparing source in /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build"
cmake -C /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -DCATKIN_ENABLE_TESTING=0 -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_PREFIX_PATH=/opt/ros/lunar -DCMAKE_INSTALL_PREFIX=/opt/ros/lunar -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build/gentoo_rules.cmake -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build/gentoo_toolchain.cmake  /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9
loading initial cache file /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /var/tmp/portage/ros-lunar/rostime-0.6.9/work/rostime-0.6.9_build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/lunar
-- This workspace overlays: /opt/ros/lunar
-- Found PythonInterp: /usr/bin/python (found version "3.4.5") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Could NOT find PY_em (missing:  PY_EM) 
CMake Error at /opt/ros/lunar/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'`

Fred

PS How do you make the "insert code" tag not mess up the way this is displayed?

**Comment by allenh1** [comment]
> Interestingly enough, updating my box now and getting this issue.

It looks like you only have `EmPy` for Python 3, so I'd try and re-emerge it, double checking your python targets.

> PS How do you make the "insert code" tag not mess up the way this is displayed?

You wrap it in backticks '```[code]```'

**Comment by flabrosse** [comment]
If the layout had not been messed up (see below), you would have been able to see that it is installed with the single 2.7 python target:

    Installed versions:  3.3-r1(11:21:44 10/02/18)(-doc PYTHON_TARGETS="python2_7 -pypy")

as I have for all my ros stuff.  In package.use I have:

    ros-*/* PYTHON_TARGETS: -* python2_7
    ros-*/* PYTHON_SINGLE_TARGET: -* python2_7

However I just spotted:

    -- Found PythonInterp: /usr/bin/python (found version "3.4.5")

in the compilation of rostime.  This is despite:

    emerge -av1 "ros-lunar/rostime"
   
    These are the packages that would be merged, in order:
    
    Calculating dependencies... done!
    [ebuild     U ~] ros-lunar/rostime-0.6.9::ros-overlay [0.6.5::ros-overlay] USE="{-test}" PYTHON_TARGETS="python2_7 -python3_5" 0 KiB

Bug?

About bits of code, I have warp them up in backticks!  That seems to work for single lines but not multiple ones...  And some just appear as the character, not being interpreted as special.  The four spaces seems to be the most reliable way of doing it, but not very easy...  I updated my initial post.

**Comment by allenh1** [comment]
My bad -- I didn't realize it wouldn't show up in my reply. Group 3 backticks to get the code to format. You can also do highlighting by putting a language next to the first pair of backticks.

```py
def My function(msg):
    print(msg)
```

**Comment by allenh1** [comment]
Since your python interpreter is python 3, you could try and eselect python 2. Otherwise, it's totally fine for empy to be python 3, as only CMake is going to use it.

**Comment by flabrosse** [comment]
OK, had to install the unstable empy-3.3.2 as the stable 3.3-r1 only has python2_7 as a possible target.  And that now emerges fine.

Thanks for the help.

**Comment by flabrosse** [comment]
Interestingly enough, I am now having exactly the same problem as before but with kdl_parser-1.12.11.  I have empy-3.3.2 installed.  Is the solution still to create a symlink by hand?

**Comment by allenh1** [comment]
>  Is the solution still to create a symlink by hand?

That's odd... It has been "working" for me for a while. I don't have the symlink anymore, at least. Can I get a bit more info?

```
$ superflore-check-ebuilds --ros-distro lunar --pkgs cmake_modules
>>>> testing gentoo package integrity
>>>> Working in temporary directory /tmp/tmpiji4b3w6
>>>> Running container with command string 'bash -c 'emaint sync -r ros-overlay &>> /tmp/tmpiji4b3w6/log.txt && emerge ros-lunar/cmake_modules &>> /tmp/tmpiji4b3w6/log.txt''...
>>>> Docker container exited.
>>>> Cleaning up temporary directory /tmp/tmpiji4b3w6
>>>>   'ros-lunar/cmake_modules': building
```

Seems to be building in the docker container. Can we get the output?

**Comment by flabrosse** [comment]
Here's the log:

``` * Package:    ros-lunar/kdl_parser-1.12.11
 * Repository: ros-overlay
 * Maintainer: hunter@openrobotics.org
 * Upstream:   clalancette@osrfoundation.org https://github.com/ros-gbp/kdl_parser/issues
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux python_targets_python2_7 userland_GNU
 * FEATURES:   preserve-libs sandbox splitdebug userpriv usersandbox
>>> Unpacking source...
>>> Unpacking kdl_parser-lunar-release-1.12.11.tar.gz to /var/tmp/portage/ros-lu
nar/kdl_parser-1.12.11/work
>>> Source unpacked in /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work
>>> Preparing source in /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-.12.11_build"
cmake -C /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build/gentoo_common_config.cmake -G Unix Makefiles -DCMAKE_INSTALL_PREFIX=/usr -D
CATKIN_ENABLE_TESTING=0 -DCATKIN_BUILD_BINARY_PACKAGE=1 -DCMAKE_PREFIX_PATH=/opt/ros/lunar -DCMAKE_INSTALL_PREFIX=/opt/ros/lunar -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_USER_MAKE_RULES_OVERRIDE=/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build/gentoo_rules.cmake -CMAKE_TOOLCHAIN_FILE=/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-.12.11_build/gentoo_toolchain.cmake  /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11
loading initial cache file /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build/gentoo_common_config.cmake
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.0
-- Using CATKIN_DEVEL_PREFIX: /var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/lunar
-- This workspace overlays: /opt/ros/lunar
-- Found PythonInterp: /usr/bin/python (found version "3.6.5") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using default Python package layout
-- Could NOT find PY_em (missing: PY_EM) 
CMake Error at /opt/ros/lunar/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
Call Stack (most recent call first):
  /opt/ros/lunar/share/catkin/cmake/all.cmake:151 (include)
  /opt/ros/lunar/share/catkin/cmake/catkinConfig.cmake:20 (include)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build/CMakeFiles/CMakeOutput.log".
 * ERROR: ros-lunar/kdl_parser-1.12.11::ros-overlay failed (configure phase):
 *   cmake failed
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_configure
 *   environment, line 4191:  Called ros-cmake_src_configure
 *   environment, line 4088:  Called cmake-utils_src_configure
 *   environment, line 1169:  Called die
 * The specific snippet of code:
 *       "${CMAKE_BINARY}" "${cmakeargs[@]}" "${CMAKE_USE_DIR}" || die "cmake failed";
 * 
 * If you need support, post the output of `emerge --info '=ros-lunar/kdl_parser-1.12.11::ros-overlay'`,
 * the complete build log and the output of `emerge -pqv '=ros-lunar/kdl_parser-1.12.11::ros-overlay'`.
 * The complete build log is located at '/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/temp/environment'.
 * Working directory: '/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11_build'
 * S: '/var/tmp/portage/ros-lunar/kdl_parser-1.12.11/work/kdl_parser-1.12.11' ```

Anything else needed?

**Comment by flabrosse** [comment]
I may well just have found what the problem was.  Just realised it is using python 3.6 but I'm in the process of removing python versions (and was moving to 3.6 when I discovered that gentoo went back to 3.5).  Clearly there is some dependency not quite working somewhere.  I'll come back after finishing the upgrade.
